version: '3.1'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: fidry_alice_data_fixtures
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    # Store data in memory to improve speed
    tmpfs:
      - /var/lib/mysql

  mongo:
    image: mongo:4.4-bionic
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: fidry_alice_data_fixtures
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # Store data in memory to improve speed
    tmpfs:
      - /data/db
